### ISSUE TITLE
Hi, presentation of Grafana Flowcharting

### ISSUE THREAD

**Issue by algenty** [obazoud/awesome-dashboard#23]
Hi,

Ma name is Arnaud and i create a plugin for Grafana to make any dashboards and drawing like legacy schema, diagrams, or more with draw.io
Some examples : 
https://play.grafana.org/d/Unu5JcjWk/flowcharting-index?orgId=1

The project : 
https://github.com/algenty/grafana-flowcharting

BR
Arnaud

**Comment by obazoud** [comment]
Please create a PR to add your link.
Thank you.
