### ISSUE TITLE
Promote Grafana to general

### ISSUE THREAD

**Issue by gianluca-sabena** [obazoud/awesome-dashboard#6]
Grafana - http://grafana.org/ - received a multiple improvements in the last year, it supports multiple backend now: elasticsearch, influxdb, opentsdb, plus custom via plugin.

I suggest to promote Grafana in group general.

**Comment by obazoud** [comment]
OK, could you please send a PR ?

**Comment by gianluca-sabena** [comment]
Yes, just done.

**Comment by obazoud** [comment]
see #7
